### ISSUE TITLE
Installation on HA core-2021.11.3 fails

### ISSUE THREAD

**Issue by swa72** [hg1337/homeassistant-dwd#1]
Installed via HACS
Restarted HA
Added integration,  showing "Please wait while Deutscher Wetterdienst (DWD) is being setup".
Waiting ... waiting ... more waiting ...
Nothing happens. 
Alternatively, an error message "Config flow doesn't work" or somesuch pops up.

Anyone any idea?

**Comment by hg1337** [comment]
Hi @swa72, I'm currently not actively distributing my extension via HACS. I guess you are probably using https://github.com/FL550/dwd_weather?

**Comment by swa72** [comment]
Bummer, you're right. I posted an issue in the wrong repo. Sorry dafür :-)
