### ISSUE TITLE
No forecast and wind_gust is missing completely since the new version

### ISSUE THREAD

**Issue by Friedi1970** [hg1337/homeassistant-dwd#12]
Since the update to v2 I have in no wind_gusts and absolutely no forecasts. I used before e.g. 
`{{ state_attr("weather.bamberg_bamberg", "forecast") [1].wind_gusts }}`
This doesn't work at all :( It seems that there is no forecast for the station id 04063. Before v2 everything worked fine.

There is also no "_daily" entity. I just have the following attributes:
```
temperature: 7.4
temperature_unit: °C
humidity: 84
pressure: 993
pressure_unit: hPa
wind_bearing: 'N'
wind_speed: 7.4
wind_speed_unit: km/h
visibility: 30.4
visibility_unit: km
precipitation_unit: mm
latest_update_utc: '2023-09-25T11:40:35.198698+00:00'
report_time_utc: ''
forecast_time_utc: '2023-09-25T09:00:00+00:00'
station_id: '04063'
station_name: bamberg
attribution: Data provided by Deutscher Wetterdienst (DWD)
friendly_name: bamberg bamberg
supported_features: 3
```

**Comment by hg1337** [comment]
Sounds like you are probably using https://github.com/FL550/dwd_weather. (Why both exist see https://github.com/hg1337/homeassistant-dwd/blob/main/questions_and_answers.md.)

However, I can still provide some information about the forecast problem: Providing forecast data via state attribute has been replaced by a new method in Home Assistant 2023.8 and deprecated in Home Assistant in 2023.9. With the new method, you have to get the forecast with a service call. This is mainly for performance reasons. For more information see https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service. They also have an example for a template. It's however not as easy as in the past.

In my integration here, I have decided for a softer migration by still providing the _daily and _hourly entities with the state attribute, but I will be forced to remove it latest in a few months as well.
