### ISSUE TITLE
weather.get_forecast is now deprecated with latest HA 2023.12

### ISSUE THREAD

**Issue by n4rrOx** [hg1337/homeassistant-dwd#17]
Hello,

with the lastest Update from HA weather integrations have to change from weather.get_forecast to weather.get_forecasts.

Please find more info here:
[https://www.home-assistant.io/blog/2023/12/06/release-202312/#backward-incompatible-changes](url)

Copy from release notes:
weather.get_forecast uses an outdated response data format and is now deprecated, pending removal in Home Assistant 2024.6.

Please use weather.get_forecasts, which supports multiple entities instead.

The output of this newer service changed slightly, as it now returns a mapping of entity IDs to lists of forecasts instead of a list of forecasts.

([@eifinger](https://github.com/eifinger) - [#102534](https://github.com/home-assistant/core/pull/102534)) ([documentation](https://www.home-assistant.io/integrations/weather))

**Comment by hg1337** [comment]
Thank you for making me aware of that. Looking into it.

**Comment by hg1337** [comment]
This integration itself is not affected by this, it affects the other side of the chain, e.g. how template sensors, automations or UI components access the weather forecasts. I have updated the examples accordingly: https://github.com/hg1337/homeassistant-dwd/commit/dd0202008ac2ae7ceaa59be9035245f85d504c5f

If you are getting this message, this means that something (e.g. an automation) has called an entity of this integration with the deprecated method, not that this integration is doing something wrong:

![image](https://github.com/hg1337/homeassistant-dwd/assets/76538974/525fb9d3-9d4e-448f-8244-0f51b4d029df)
