### ISSUE TITLE
How to set up a lovelace card as shown in your screenshot?

### ISSUE THREAD

**Issue by 7wells** [hg1337/homeassistant-dwd#20]
Hello!

I understand that my question is not an issue and hope that you do not mind providing me with some hints into the right direction.

How can I set up a lovelace card as shown in your screenshot?
https://github.com/hg1337/homeassistant-dwd/blob/main/images/screenshot_entity.png

I would like to have the current situation shown above and below in 2 columns (left: daily + right: hourly) more days/hours. Currently, with the standard weather card, I get only 5 days or 5 hours maximum and only in separate cards.

Thank you so much for your help!

**Comment by hg1337** [comment]
Hi @7wells, the screenshot you mention is the details page of the weather entity, e.g. when you click/tap on a weather card. Unfortunately, I don't know a Lovelace card that looks like that. For Lovelace, I use this third party weather card: https://github.com/bramkragten/weather-card It's at least more flexible than the built-in one, e.g. it can show more than 5 forecasts (I have configured a panel that shows 14 hourly forecasts). You can find an example configuration at https://github.com/hg1337/homeassistant-dwd/blob/main/setup.md. However, it cannot produce the result from the screenshot as it uses the horizontal layout, too.

**Comment by hg1337** [comment]
I'm closing the issue, but feel free to continue the discussion.

**Comment by hg1337** [comment]
Thanks @7wells for the link, the clock-weather-card indeed looks very helpful, too. 👍 

Yes, you can try. As the UI elements are all there already, it's maybe not so complicated for them to create a Lovelace card out of it.
