### ISSUE TITLE
Always "Unknown" as state for weather.notzingen

### ISSUE THREAD

**Issue by Mikrofarad** [hg1337/homeassistant-dwd#21]
With _weather.stuttgart_echterdingen_ it works!
![PicPick_20240417_070638](https://github.com/hg1337/homeassistant-dwd/assets/19363324/e4c5e1b9-e7c8-4f16-be38-f07e7be6ebd3)

**Comment by hg1337** [comment]
Some stations unfortunately have this issue. Sometimes only temporary for a few weeks or months. `weather.stuttgart_echterdingen` had this as well a few months ago but then they fixed it after some time. You can verify that in the original data, the `present_weather` column is always empty, so nothing this integration can directly to about it: https://opendata.dwd.de/weather/weather_reports/poi/Q061_-BEOB.csv

What you can do however to mitigate this is that you change the configuration of this station (Settings -> Devices & Services -> Deutscher Wetterdienst -> Integration entries (list on the right side) -> Notzingen -> Configure) to fall back to forecasted values for missing measurement data which also works for the state/condition:

![image](https://github.com/hg1337/homeassistant-dwd/assets/76538974/6b797727-18d2-4632-9504-5f287d426db4)

![image](https://github.com/hg1337/homeassistant-dwd/assets/76538974/adee1e9f-be3f-4648-8574-c53694331cb1)

Then it shows the forecasted value as state/condition:

![image](https://github.com/hg1337/homeassistant-dwd/assets/76538974/b9fe07a5-b643-46be-9dd9-4eec099dff89)

This is not the default configuration so you have the full control over what happens, so you can choose to either use a different station or use the fallback mechanism.

PS: You should migrate to the new entities without `_daily` and `_hourly` suffix, see https://github.com/hg1337/homeassistant-dwd/blob/2024.1.0/migration.md

**Comment by Mikrofarad** [comment]
Thanks a lot. I completely forgot to migrate 😲
For Notzingen I never saw anything else than "unknown" for the state. But with your guide everything works like a charm 😃 Great job 👍

**Comment by hg1337** [comment]
Thank you, happy that I could help. 😊
