### ISSUE TITLE
Home Assistant Core "Warnung"... Detected code that calls async_forward_entry_setup for integration dwd...

### ISSUE THREAD

**Issue by Baxxy13** [hg1337/homeassistant-dwd#25]
After updating Homeassistant to 2024.7.1 i got the following warning that mentions this custom-integration:

> Detected code that calls async_forward_entry_setup for integration dwd with title: Berlin-Tempelhof and entry_id: be0dec4414d7653030f0a411126d0cdf, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

Actually it's only a warning and the integration works without problems.

Thanks for your work on this.

**Comment by ChristophCaina** [comment]
fixed with PR #26

**Comment by ChristophCaina** [comment]
I think, this is the code that needs to be checked:

```
async def async_setup_entry(hass: HomeAssistant, config_entry: ConfigEntry) -> bool:
    """Set up DWD as config entry."""

    config_entry.async_on_unload(config_entry.add_update_listener(update_listener))

    coordinator = DwdDataUpdateCoordinator(hass, config_entry)
    await coordinator.async_refresh()

    if not coordinator.last_update_success:
        raise ConfigEntryNotReady

    hass.data[DOMAIN][config_entry.entry_id] = coordinator

    hass.async_create_task(
        hass.config_entries.async_forward_entry_setup(config_entry, PLATFORMS)
    )
    return True
```

especially: `hass.config_entries.async_forward_entry_setup(config_entry, PLATFORMS)` should probably be changed to `await hass.config_entries.async_forward_entry_setup()`

For another integration, it was required to remove the complete block "hass.async_create_task(..."
But here, the integration stops working all the time when I try to fix this... sorry

**Comment by hg1337** [comment]
Thank you for reporting this @Baxxy13 and @ChristophCaina for the hint, will look into it.

**Comment by hg1337** [comment]
> I still get that warning (2024.4.0). Is this integration still maintained?

Yes, sorry, was very busy with other topics recently. Will provide an update soon.

**Comment by hg1337** [comment]
Fixed in release [2024.9.0](https://github.com/hg1337/homeassistant-dwd/releases/tag/2024.9.0).

**Comment by Baxxy13** [comment]
Looks good. Thanks for the update.

**Comment by hg1337** [comment]
> Looks good. Thanks for the update. 

Thank you!
