### ISSUE TITLE
I can't find a precipitation_probability anywhere in the integration

### ISSUE THREAD

**Issue by ars4l4n** [hg1337/homeassistant-dwd#29]
Neither can I find an entity with that name in HA. How do I access the forecasts for that?

**Comment by JueK3y-Prv** [comment]
Have a look at this: https://github.com/hg1337/homeassistant-dwd/blob/main/questions_and_answers.md

You can access it via `weather.get_forecasts`.
If you want to use it for an automation, you need to create an template. This is described on the Q&A page linked above
