### ISSUE TITLE
HA-core 2023.3.0.b5 warning recorder - exceed max. size of attributes

### ISSUE THREAD

**Issue by S-Przybylski** [hg1337/homeassistant-dwd#6]
Hi,
there is a warning visbile since updated to the HA march 2023 beta:

HA-Version: Home Assistant 2023.3.0b5

Log:
````
Logger: homeassistant.components.recorder.db_schema
Source: components/recorder/db_schema.py:491
Integration: Recorder (documentation, issues)
First occurred: 08:32:25 (1 occurrences)
Last logged: 08:32:25

State attributes for weather.norvenich_flugplatz_hourly exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
````

**Comment by hg1337** [comment]
@S-Przybylski thank you for bringing this to my attention. I will look into this.

**Comment by S-Przybylski** [comment]
(Das ist doch selbstverständlich)

**Comment by S-Przybylski** [comment]
I can live with the fact, that the data is not stored in the history, especially if we talk about predicted values....
I am not sure, if a code update needs to be done.

**Comment by hg1337** [comment]
Originally, I was going to add a configuration option to limit the number of forecasts. However, I haven't seen the warning in a while and with the new mechanism to provide forecasts via async methods instead of properties this should at least for the new combined entity not happen any more.
