### ISSUE TITLE
State of entities are not set

### ISSUE THREAD

**Issue by schnulliepups** [hg1337/homeassistant-dwd#8]
Hi,
I added the integration and set everything up. Now after the first day I noticed that the state of the created entities are "unknown" for both daily and hourly entity. Forecast attributes are filled with valid values.
Is there any configuration required or did I missed something?

![image](https://user-images.githubusercontent.com/65162916/234768862-d6643aed-1f51-4b5c-a12d-a7901050f2bc.png)
![image](https://user-images.githubusercontent.com/65162916/234768420-fe4b07eb-6cd5-4779-8439-c3a5fd6f46dc.png)
![image](https://user-images.githubusercontent.com/65162916/234768577-c55cecde-7245-48f2-8bcb-babdd4ed5a37.png)

**Comment by hg1337** [comment]
Hi,

unfortunately, some stations do not provide weather conditions (sunny, rainy etc.) together with the measurements.

Station with weather conditions (column "present_weather" filled):
https://opendata.dwd.de/weather/weather_reports/poi/10739-BEOB.csv

Station without weather conditions (column "present_weather" has not data):
https://opendata.dwd.de/weather/weather_reports/poi/10738-BEOB.csv

I suppose your station is like the second one (10738). If the "present_weather" is filled and it still doesn't work, please give me your station number so I can check.

However, there is still something you can do to use your station as good as possible in this case. Go to the configuration dialog for your station on the Integrations page (https://my.home-assistant.io/redirect/integrations/) and configure to fall back to forecast data:

![image](https://user-images.githubusercontent.com/76538974/234986383-51ba757b-f1c1-44fe-ac94-290047dd7062.png)

This will still use measurement data where possible, but e.g. use the forecast for the current hour e.g. for the weather conditions when they are missing.

**Comment by schnulliepups** [comment]
Thank you for your quick response! Yes you are right the station I am using does not provide the info. Switched to the second option as you suggested and I can see it now.

Great integration! Thanks for your work!
