### ISSUE TITLE
Conditions/states do not match the mdi Icon-Naming - Listing of all Conditions?

### ISSUE THREAD

**Issue by dafunkydan** [hg1337/homeassistant-dwd#9]
Thanks for this great Addon! Gives me quite reliable Data and Forecasts!

As i want to display Icons for the corresponding Weatherconditions, i found out that the naming doesn't (always) match the mdi Naming.
For Example '**partlycloudy**' vs _(mdi:weather-)_'**partly-cloudy**'.
In Order to create a Look-Up-Table a Listing of all possible Weatherconditions would be really helpful.
May i kindly ask if you would have such a Summary? :-)

**Comment by hg1337** [comment]
Thank you @dafunkydan!

The conditions/states should (hopefully ;) ) match the ones documented at https://developers.home-assistant.io/docs/core/entity/weather/#recommended-values-for-state-and-condition as I am using the constants provided by Home Assistant Core.

They are the ones imported at https://github.com/hg1337/homeassistant-dwd/blob/main/custom_components/dwd/const.py line 5:

```python
from homeassistant.components.weather import (
    ATTR_CONDITION_CLEAR_NIGHT,
    ATTR_CONDITION_CLOUDY,
    ATTR_CONDITION_EXCEPTIONAL,
    ATTR_CONDITION_FOG,
    ATTR_CONDITION_HAIL,
    ATTR_CONDITION_LIGHTNING,
    ATTR_CONDITION_LIGHTNING_RAINY,
    ATTR_CONDITION_PARTLYCLOUDY,
    ATTR_CONDITION_POURING,
    ATTR_CONDITION_RAINY,
    ATTR_CONDITION_SNOWY,
    ATTR_CONDITION_SNOWY_RAINY,
    ATTR_CONDITION_SUNNY,
    ATTR_CONDITION_WINDY,
    ATTR_CONDITION_WINDY_VARIANT,
)
```

Which should be coming from https://github.com/home-assistant/core/blob/dev/homeassistant/components/weather/__init__.py line 54:

```python
ATTR_CONDITION_CLEAR_NIGHT = "clear-night"
ATTR_CONDITION_CLOUDY = "cloudy"
ATTR_CONDITION_EXCEPTIONAL = "exceptional"
ATTR_CONDITION_FOG = "fog"
ATTR_CONDITION_HAIL = "hail"
ATTR_CONDITION_LIGHTNING = "lightning"
ATTR_CONDITION_LIGHTNING_RAINY = "lightning-rainy"
ATTR_CONDITION_PARTLYCLOUDY = "partlycloudy"
ATTR_CONDITION_POURING = "pouring"
ATTR_CONDITION_RAINY = "rainy"
ATTR_CONDITION_SNOWY = "snowy"
ATTR_CONDITION_SNOWY_RAINY = "snowy-rainy"
ATTR_CONDITION_SUNNY = "sunny"
ATTR_CONDITION_WINDY = "windy"
ATTR_CONDITION_WINDY_VARIANT = "windy-variant"
```

**Comment by dafunkydan** [comment]
Awesome! Thank you so much, it works like a charm (at least, for the Conditions i can check right at the Moment :-) )
So, the HA States do not completly match the mdi Icon-Naming - weird. Anyway, i am happy now!
